version: 2

multi-ecosystem-groups:
  default:
    versioning-strategy: "auto"
    update-types: [ "version-update:semver-patch", "version-update:semver-minor" ]
    reviewers: [ "sator-imaging" ]
    labels: [ "dependabot" ]
    commit-message:
      prefix: "deps"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 7
      semver-major-days: 21
      semver-minor-days: 14
      semver-patch-days: 7
    open-pull-requests-limit: 10

updates:
  - package-ecosystem: "npm"
    multi-ecosystem-group: "default"
    directory: "/"
  - package-ecosystem: "bun"
    multi-ecosystem-group: "default"
    directory: "/"
  - package-ecosystem: "nuget"
    multi-ecosystem-group: "default"
    directory: "/"
